services:
  db:
    container_name: ru-facil-db
    image: postgres:13
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-ru-facil:/var/lib/postgresql/data
    networks:
      - ru-facil-network
  web:
    container_name: ru-facil-web
    build: .
    ports:
      - "3333:3333"
    depends_on:
      - db
    networks:
      - ru-facil-network
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PORT
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  postgres-ru-facil:

networks: 
  ru-facil-network:
    driver: bridge
